# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-22 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eindspel', '0003_auto_20170622_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piecestatic',
            name='currentSpace',
        ),
    ]
