# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-03 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eindspel', '0004_remove_piecestatic_currentspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='currentSpace',
            field=models.CharField(max_length=255),
        ),
    ]
