# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-03 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eindspel', '0005_auto_20170803_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piece',
            name='player',
        ),
        migrations.DeleteModel(
            name='Piece',
        ),
    ]
